services:
  train:
    build: .
    volumes:
      - ./data:/app/data:ro
      - ./src/experiments/experiments_template.py:/app/src/experiments/experiments_template.py:ro
      - ./experiments:/app/experiments
      - ./results:/app/results
    command: ["train", "/app/src/experiments/experiments_template.py"]

  eval:
    build: .
    volumes:
      - ./data:/app/data:ro
      - ./experiments:/app/experiments
      - ./results:/app/results
    environment:
      EXPERIMENTS_URL: "https://drive.google.com/uc?export=download&id=1X_scCj_fxi7nLO-2wqFQWrAyGuwpomWE"
    command: ["bash", "-lc", "download_experiments.sh && python -m src.main evaluate"]

  analyse:
    build: .
    volumes:
      - ./data:/app/data
      - ./experiments:/app/experiments
      - ./results:/app/results
    environment:
      EXPERIMENTS_URL: "https://drive.google.com/uc?export=download&id=1X_scCj_fxi7nLO-2wqFQWrAyGuwpomWE"
    command: ["bash", "-lc", "download_experiments.sh && python -m src.main analyse"]