services:
  train:
    build: .
    volumes:
      - ./data:/app/data:ro
      - ./src/experiments/experiments_template.py:/app/src/experiments/experiments_template.py:ro
      - ./experiments:/app/experiments
      - ./results:/app/results
    command: ["train", "/app/src/experiments/experiments_template.py"]

  eval:
    build: .
    volumes:
      - ./data:/app/data:ro
      - ./experiments:/app/experiments
      - ./results:/app/results
    command: ["evaluate"]

  analyse:
    build: .
    volumes:
      - ./data:/app/data
      - ./experiments:/app/experiments
      - ./results:/app/results
    command: ["analyse"]